application: linkpeelr-hrd
version: 2
runtime: python27
api_version: 1
default_expiration: "1d"
threadsafe: false

handlers:

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /static
  static_dir: static

- url: /.*
  script: index.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest