application: linkpeelr
version: 1
runtime: python
api_version: 1

default_expiration: "1d"

handlers:

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  
- url: /static
  static_dir: static
  
- url: /api
  script: api.py 
  
- url: /.*
  script: index.py
  
