application: linkpeelr-hrd
version: 2
runtime: python27
threadsafe: true
api_version: 1

default_expiration: "14d"

builtins:
- remote_api: on
- appstats: on

handlers:
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /(apple-touch-icon.*\.png)
  static_files: static/img/\1
  upload: static/img/(app-touch-icon.*\.png)
  
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  
- url: /humans.txt
  static_files: static/humans.txt
  upload: static/humans.txt
  
- url: /css
  static_dir: static/css
  
- url: /img
  static_dir: static/img
 
- url: /js
  static_dir: static/js 

- url: /font/(.*\.eot)
  static_files: static/font/\1
  upload: static/font/(.*\.eot)
  mime_type: font/eot

- url: /font
  static_dir: static/font

- url: /.*
  script: app.application
  
libraries:
- name: jinja2
  version: "2.6"
  
- name: webapp2
  version: "2.5.1"
  
- name: lxml
  version: latest

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?.*\.less$
  
